### ISSUE TITLE
Moving npm packages to root

### ISSUE THREAD

**Issue by szepeviktor** [mnapoli/simple-s3#2]
Would you welcome a PR that moves `package.json` to the project root?

**Comment by mnapoli** [comment]
Why would you want to do that?

**Comment by szepeviktor** [comment]
Simply I've never seen npm config files outside package root.
Do you know a package with it? (except monorepos)

**Comment by szepeviktor** [comment]
This seems to a production dependency.
https://github.com/mnapoli/simple-s3/blob/606264b15eb9815ae4c6d8c21150c01c6e0f0caf/tests/package.json#L2-L4

**Comment by mnapoli** [comment]
Now you have seen it 😛 

More seriously these are dependencies for tests, moving them  to the root wouldn't improve anything, it would just make the package more confusing to use for some users. The whole point as well of the package is that it's very small and self-contained. Tests are not part of it, so I'd rather encapsulate everything needed for tests in that directory.
